apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: staticauth
spec:
  replicas: 2
  selector:
    matchLabels: { app: auth-service }
  template:
    metadata:
      labels: { app: auth-service }
    spec:
      containers:
      - name: auth-service
        image: iamyogeshjagtap/auth-service:latest
        env:
          - name: USER_SERVICE_URL
            value: http://user-service:4000
        ports:
          - containerPort: 5000
        livenessProbe:
          httpGet: { path: /healthz, port: 5000 }
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet: { path: /healthz, port: 5000 }
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: staticauth
spec:
  selector:
    app: auth-service
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP

